### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by NLLAPPS** [adroitandroid/Near#1]
Hi, is this project still active?

**Comment by adroitandroid** [comment]
I'm listening, tell me

**Comment by NLLAPPS** [comment]
I haven't seen recent update so I was wondering If there will be any other changes. I am planing to implement some sort of file transfer over WifiDiret and looking for a stable library

**Comment by adroitandroid** [comment]
Hasn't been active as I've not used it much since. File transfer is on
Todo, currently you can try it by tweaking the sample app code but there's
no notification about progress and all. Breaking the stream down and all is
still left.
