### ISSUE TITLE
Pure Java Equivalent

### ISSUE THREAD

**Issue by DatL4g** [adroitandroid/Near#11]
I need a pure Java equivalent for Desktop applications
But I'm running into some problems implementing this
(especially implementing the server)

It would be very cool if you took care of it and created a repository for it.
I would of course also help as much as possible if it is difficult in terms of time.

**Comment by DatL4g** [comment]
@adroitandroid 
**I got the discovery working**

However the devices see each other only for a millisecond (i see it in console output)
I think it has something to do with the threads I'm running but I'm not sure

Could you please contact me **datlag.developer@gmail.com**
I would share the code with you and you could maybe take a look

**Comment by DatL4g** [comment]
Sorry that I might be a bit annoying but I have already managed it

So don't need your help for now

**Comment by adroitandroid** [comment]
seeing these only now, sorry. Really cool that you could make it work! lemme know if you need any help, if there's a github repo, I can watch for sure

**Comment by DatL4g** [comment]
Hey, I have a github repo with a project
[HotDrop-Desktop](https://github.com/DATL4G/HotDrop-Desktop)
And I have a problem with discovery.
It works but I can only find one device 

e.g. 3 devices: 2 Smartphones and 1 PC
The smartphones can detect each other and the PC
However the PC can only find 1 Smartphone (sometimes Smartphone 1 and sometimes Smartphone 2)

Maybe you can take a look
The code is located under [src/main/kotlin/p2p/cu2](https://github.com/DATL4G/HotDrop-Desktop/tree/master/src/main/kotlin/p2p/cu2)
