### ISSUE TITLE
Crashes app after going to background

### ISSUE THREAD

**Issue by anpez** [adroitandroid/Near#14]
OnPause of my activity I do:
```
    if (nearDiscovery.isDiscovering) {
      nearDiscovery.stopDiscovery()
    }
    if (nearDiscovery.isDiscoverable) {
      nearDiscovery.makeNonDiscoverable()
    }
    if (nearConnect.isReceiving) {
      nearConnect.stopReceiving(false)
    }
```

but still it crashes with this error:
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent         at com.adroitandroid.near.connect.server.TcpServerService.onStartCommand(TcpServerService.kt)
```

**Comment by AndroFlo** [comment]
Hi, @ANPez  the intent parameter of the onStartCommand in TcpServerService class is null but set as no nullable. You can make it non nullable because the [documentation ](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)) say

> This may be null if the service is being restarted after its process has gone away, and it had previously returned anything except START_STICKY_COMPATIBILITY.

**Comment by anpez** [comment]
That's right, the TcpServerService is crashing when the system restarts the service. I think we should make it nullable to handle that case
